arb-dir: lib
template-arb-file: app_en.arb
output-localization-file: breez_translations.dart
output-class: BreezTranslations
output-dir: lib/generated
synthetic-package: false
untranslated-messages-file: untranslated_messages.txt
